# Generated by Django 4.1 on 2022-08-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_field', models.TextField(blank=True, default='Text', max_length=256)),
            ],
            options={
                'verbose_name': 'example_model',
                'verbose_name_plural': 'example_models',
                'db_table': 'example_models',
                'abstract': False,
            },
        ),
    ]
