name: 1 - Test Django

on:
  workflow_dispatch:

jobs:
  django_test:
    runs_on: ubuntu_latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Django tests
        run: python manage.py test